### ISSUE TITLE
review code of coduct and contributing docs

### ISSUE THREAD

**Issue by amchagas** [FOSH-following-demand/map_fosh_demand#5]
The first draft of [code of conduct](https://github.com/amchagas/map_fosh_demand/blob/master/CODE_OF_CONDUCT.md) and [contributing](https://github.com/amchagas/map_fosh_demand/blob/master/CONTRIBUTING.md) docs are available. An extra pair of eyes for review are welcome!

**Comment by emdupre** [comment]
:tada: I'm so excited to see these two files added ! This project is already zooming along :rocket: 
I thought I'd just share a few general thoughts:

- The Contributor Covenant code of conduct is a great choice ! The one thing I'd say is that their template enforcement section is rather vague (deliberately, so that it can apply to a wide range of projects !). If you have a specific enforcement structure in mind, it'd be great to add that in or to update their text !

- The contributing guidelines are list some really fantastic _kinds_ of contributions you're looking for, but I think a little more detail on how each of those contributions could be executed would be helpful ! That is, if someone would like to translate the survey but is totally new to GitHub, what would it mean to "fork the repo" ? Where would they find resources to do that ?
You can see an example of how I've tried to walk through that process [here](https://github.com/ME-ICA/tedana/blob/master/CONTRIBUTING.md), but there are obviously many other (and better !) examples in the wild. 

Hopefully this helps a little bit ! Let me know what you think of these ideas. I'm excited to see what's next ! :sparkles:

**Comment by amchagas** [comment]
Hi!
thanks for your comments, certainly very helpful! 
I made some changes, which I hope are incorporating your suggestions and comments.
